### PR TITLE
Fix stickybits not saving instances when `useStickyClasses: false`

### LINKED ISSUE #188: stickybits.cleanup() not working correctly?
I'm using stikybits on a new website and I need to make sure it only applies the `position` and `top` properties when on a given breakpoint.

I've seen there's an example to the cleanup method (https://codepen.io/yowainwright/pen/gRgdep), the problem with this is that you're using a class selector that has no elements on the document that match (`.child-1`). The selector should be `.child` instead. First issue: solved.

Now, what I would expect is to be able to cleanup stickybits no matter what its config is. At least that what it seems you should be able to do when looking at this: https://github.com/dollarshaveclub/stickybits#stickybits-cleanup

The problem here is that stickybits doesn't clean anything unless you're using `useStickyClasses: true` (which is on the CodePen example I linked to earlier). This happens be because if you don't add this property, stickybits won't save the instances.

I think the conditional here should be changed to also save those instances to stickybits so we can clean them up and avoid having scroll listeners when we don't need to add/remove any CSS classes.

https://github.com/dollarshaveclub/stickybits/blob/f33c18c776187bd94ec315a21a45ba9243c3b1ee/src/stickybits.js#L85

----

Also it seems you have some redundant code in this two lines: https://github.com/dollarshaveclub/stickybits/blob/f33c18c776187bd94ec315a21a45ba9243c3b1ee/src/stickybits.js#L74 https://github.com/dollarshaveclub/stickybits/blob/f33c18c776187bd94ec315a21a45ba9243c3b1ee/src/stickybits.js#L112

### PR DESCRIPTION
**Pull request by hacknug**
This PR should fix the issue described in #188.

Here's a couple videos I recorded of stickybits pre/post fix to show how it was affecting me. Changing the location of the dev tools triggers the breakpoint change that enables/disables stickybits.

Bug: https://streamable.com/wvkx1
Fix: https://streamable.com/nznpm

Closes #188.

### CODE REVIEW

**Comment by yowainwright** [comment]
@hacknug thanks you! I will look asap.

File: src/stickybits.js [hunk 1]
```diff
@@ -84,13 +84,13 @@ function Stickybits(target, obj) {
     if (vp === 'top' && !ns) styles[vp] = `${p.stickyBitStickyOffset}px`
     if (pv !== 'fixed' && p.useStickyClasses === false) {
       styles.position = pv
-    } else {
+    } else if (pv !== 'fixed') {
```
Comment (yowainwright) [inline src/stickybits.js]: 🔥
